sudo: required
dist: xenial
services: docker
script:
- docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data blang/latex:ubuntu latexmk -pdf resume.tex
deploy:
  provider: releases
  api_key:
    secure: cjn+VXHS+X3tuHc/DdCGeUulMan8Q6F2jk48LJCP8r43d3YhtgWo0+JHTShE82n27BUKF62BtG45+ZtEubQU9XZZaEf9EdyXWohQ/RfZpDOC+IFPhVe99nNKlw6JLBTeRlXDcXYeF468LuieyfKY4RSsuxzpq29hQw75Xwe22MUq3ANfx1Hq0rwst8/gRgbepwtA4hf9cet173zscTPWGj4NATnu7vD+xbyzjmcqtClRth6FCpTsp1iaSaEU+1GFIyCV/TiLjYGJPgxqJN7EutIPwkO795382KXVj0e/Ca+YBvzV9Yc8uAgW9u0wGuZpeKUHh2nTATAv3NReRFy2vuUbSi2lmlcY8BQ4RhUL/Rt5Mf+y/9sqAeKobkJBdkfVLao+J8RhO8KPa+UNPCgEWldkXG20jmgPETSmdUENZRMd2D0yKKe5XxaxPz04Itih+AAwLmPpDnBZ/hRjtRT57wBYtV1VhlMvTqrmB/VZxbY2M9daogHlB7+yZiXwdDFtJ7yhOeeozkT2leUOQ0QzK3Y8dLp9KRLg/euXusBFe7xahpMM0H2jeqxOMDLe0gJDEcMNWBDzACgIcFjfHvF5nkWZEEVAcsbCzN6gkcZ/NuvnMMMm+rHLSXNUUlFKlRQjiWXGwiodBH2qAavyarV2c8T7H+vrJbRkribSw+IXM5M=
  file: resume.pdf
  skip_cleanup: true
  on:
    tags: true